### ISSUE TITLE
Detection errors after applying DropDetectionItemTransformation

### ISSUE THREAD

**Issue by slincoln-aiq** [SigmaHQ/pySigma#104]
After applying the `DropDetectionItemTransformation` to some Sigma rules and attempting to convert the detections to a dict, or convert the Sigma rule with a backend, the following error appears:
```
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/pySigma/Testing/test.py", line 22, in <module>
    pprint(sigma_rule.detection.to_dict())
  File "/Users/user/PycharmProjects/pySigma/Testing/venv/lib/python3.8/site-packages/sigma/rule.py", line 488, in to_dict
    detections = {
  File "/Users/user/PycharmProjects/pySigma/Testing/venv/lib/python3.8/site-packages/sigma/rule.py", line 489, in <dictcomp>
    identifier: detection.to_plain()
  File "/Users/user/PycharmProjects/pySigma/Testing/venv/lib/python3.8/site-packages/sigma/rule.py", line 374, in to_plain
    raise sigma_exceptions.SigmaValueError("Can't convert detection into plain value because it contains mixed detection item types.", source=self.source)
sigma.exceptions.SigmaValueError: Can't convert detection into plain value because it contains mixed detection item types.
```

This is the code I'm attempting to run with pySigma v0.9.5, which includes a url for the rule I'm using:
```python
import requests
from sigma.rule import SigmaRule
from sigma.processing.pipeline import ProcessingPipeline, ProcessingItem
from sigma.processing.transformations import DropDetectionItemTransformation
from sigma.processing.conditions import ExcludeFieldCondition
from pprint import pprint

sigma_rule_str = requests.get('https://raw.githubusercontent.com/SigmaHQ/sigma/master/rules/windows/process_creation/proc_creation_win_certutil_download.yml').text

sigma_rule = SigmaRule.from_yaml(sigma_rule_str)
pipeline = ProcessingPipeline(
    name="Test DropDetectionItemTransformation Pipeline",
    items=[
        ProcessingItem(
            identifier="Test DropDetectionItemTransformation Item",
            transformation=DropDetectionItemTransformation(),
            field_name_conditions=[ExcludeFieldCondition(['Image'])],
        )
    ]
)
pipeline.apply(sigma_rule)
pprint(sigma_rule.detection.to_dict())
```

At the time of the Exception, `sigma_rule.detection.detection` is the following:
```python
{'selection_flags': SigmaDetection(parent=None, detection_items=[], source=None, item_linking=<class 'sigma.conditions.ConditionAND'>),
 'selection_http': SigmaDetection(parent=None, detection_items=[], source=None, item_linking=<class 'sigma.conditions.ConditionAND'>),
 'selection_img': SigmaDetection(parent=None, detection_items=[SigmaDetection(parent=None, detection_items=[SigmaDetectionItem(parent=None, applied_processing_items=set(), field='Image', modifiers=[<class 'sigma.modifiers.SigmaEndswithModifier'>], value=[(<SpecialChars.WILDCARD_MULTI: 1>, '\\certutil.exe')], value_linking=<class 'sigma.conditions.ConditionOR'>, source=None)], source=None, item_linking=<class 'sigma.conditions.ConditionAND'>), SigmaDetection(parent=None, detection_items=[], source=None, item_linking=<class 'sigma.conditions.ConditionAND'>)], source=None, item_linking=<class 'sigma.conditions.ConditionOR'>)}
```

This appears to be because in `rule.py` on line 353 and 357:
```python
       detection_items = [     # first convert all detection items into a Python representation.
            detection_item.to_plain()
            for detection_item in self.detection_items
        ]
       detection_items_types = {   # create set of types for decision what has to be returned
            type(detection_item)
            for detection_item in detection_items
        }
... # below checks for len of detection_item_types, raise exception if more than 1
```
when the detection items and types are found for the processed rule, in one of the detections the `detection_items` found is `[{'Image|endswith': '\\certutil.exe'}, None]` which results in `detection_items_types` as `{<class 'NoneType'>, <class 'dict'>}`
. Afterwards, the len of the detection_item_types list is checked, and if its greater than 1 an error is thrown.

I'm unsure what the root cause is at this moment, but adding the following to `DropDetectionItemTransformation` in `transformations.py` solves this issue:
```python
    def apply(self, pipeline: "sigma.processing.pipeline.ProcessingPipeline", rule: SigmaRule) -> None:
        super().apply(pipeline, rule)
        for detection in rule.detection.detections.values():
            self._delete_detection(detection)

    def _delete_detection(self, detection: SigmaDetection):
        for i, detection_item in enumerate(detection.detection_items):
            if isinstance(detection_item, SigmaDetection):  # recurse into nested detection items
                if detection_item.detection_items:  # if we have detection items, recurse
                    self._delete_detection(detection_item)
                else:  # If no detection, del object completely
                    del detection.detection_items[i]
            else:  # Found SigmaDetectionItem, check if []
                if not detection.detection_items:
                    del detection.detection_items[i]
                continue
```
This ensures each empty SigmaDetection and SigmaDetectionItem object is completed deleted from the SigmaRule and not found as a detection item  in `to_plain()`. Output after adding the above to `transformations.py` and re-running my test code above:
```python
{'condition': 'all of selection_*',
 'selection_flags': None,
 'selection_http': None,
 'selection_img': {'Image|endswith': '\\certutil.exe'}}
```
I have not thoroughly tested the consequences of this change, or if SigmaDetection and SigmaDetectionItem's are ever intended to be completely deleted, but it appears to not have any unintended consequences so far. Would be happy to make a PR with the changes if you'd like.

**Comment by thomaspatzke** [comment]
Hi! Thanks for bringing this up. I try to reproduce it as test case but believe this is indeed a bug because I didn't considered this as case while developing this transformations.

The DropDetectionItemTransformation is intended to be used in specific cases where a field from the Sigma rule is not applicable to the target data schema. One [example where I used this is the CrowdStrike processing pipeline](https://github.com/SigmaHQ/pySigma-pipeline-crowdstrike/blob/a22b65f99a96975dd35f713d7c6a57d5113fb9d7/sigma/pipelines/crowdstrike/crowdstrike.py#L78) (it's also the initial reason for creating this transformation) is the *Initiated* field in network connection events that is inhertied from the Sysmon event schema into Sigma, but doesn't exists in the CrowdStrike data model. The important thing here is, that the field is not simply removed, as this would change the semantics of the converted detection, but mapped to different event types for both possible values of the *Initiated* field: [NetworkConnectionIP4](https://github.com/SigmaHQ/pySigma-pipeline-crowdstrike/blob/a22b65f99a96975dd35f713d7c6a57d5113fb9d7/sigma/pipelines/crowdstrike/crowdstrike.py#L49) if the value of *Initiated* is *true* and [NetworkReceiveAcceptIP4](https://github.com/SigmaHQ/pySigma-pipeline-crowdstrike/blob/a22b65f99a96975dd35f713d7c6a57d5113fb9d7/sigma/pipelines/crowdstrike/crowdstrike.py#L59) otherwise.

As discussed in the other location, I strongly recommend to not just dropping fields that are not supported because this would change the detection semantics. Nevertheless, I think there can be valid cases where a detection or detection item might be empty at the final processing, so the pull request would be helpful here to fix this issue.
