### ISSUE TITLE
Missing __init__.py

### ISSUE THREAD

**Issue by pkyriakis** [SigmaHQ/pySigma#143]
The pip package is missing the top-level _init__.py file which results in not being able to import the module. 

`ModuleNotFoundError: No module named 'sigma.rule'; 'sigma' is not a package`

**Comment by thomaspatzke** [comment]
It's intentional because pySigma is structures as [namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) that allows to split certain parts like backends or processing pipelines into separate projects that implement their parts inside the *sigma* namespace.

Please use specific import like `from sigma.rule import SigmaRule`.

**Comment by pkyriakis** [comment]
Unfortunately, I still get the same error:

```
Traceback (most recent call last):
  File "/Users/pkyriaki/code/dab/testing/sigma.py", line 1, in <module>
    from sigma.rules import SigmaRule
  File "/Users/pkyriaki/code/dab/testing/sigma.py", line 1, in <module>
    from sigma.rules import SigmaRule
ModuleNotFoundError: No module named 'sigma.rules'; 'sigma' is not a package
```

**Comment by thomaspatzke** [comment]
Which Python version so you use?
