### ISSUE TITLE
Support for snake case transformation on the field.

### ISSUE THREAD

**Issue by suryamajhi** [SigmaHQ/pySigma#309]
For SIEM which converts the event fields into snake_case would benefit if there were an inbuilt supported snake_case transformation.
Eg: 
```
ParentImage -> parent_image
OriginalFile -> original_file
Image -> image
```

**Comment by suryamajhi** [comment]
Hi @thomaspatzke ,
I recently submitted a pull request (PR #310) to add support for snake_case transformation in pySigma. This feature is particularly beneficial in SIEM contexts, where event field normalization is crucial, and snake_case is a widely adopted convention.

The implementation follows the existing project structure and aims to be as non-intrusive as possible. I’d love to hear your feedback or suggestions on improving the implementation to align better with the project's goals.

Thank you for taking the time to review this! Please let me know if there’s anything I can clarify or adjust further.

**Comment by thomaspatzke** [comment]
Hi! Sorry for letting you wait, I was busy with some other stuff. The pull request is great, just a small change (formatting with black) was required, I've already done it. Thanks for your contribution!

Because pySigma main branch is currently in an intermediate state with breaking changes before 1.0 release the addition will be contained in the 1.0 release.
