### ISSUE TITLE
TODO: Trademark Test/Validator

### ISSUE THREAD

**Issue by nasbench** [SigmaHQ/pySigma#86]
This issue is just so that when we migrate the tests from [test_rules.py](https://github.com/SigmaHQ/sigma/blob/master/tests/test_rules.py) we need to also include the test `test_legal_trademark_violations` that solved the issue [#1028](https://github.com/SigmaHQ/sigma/issues/1028)

**Comment by thomaspatzke** [comment]
To be honest, I intentionally didn't ported this test yet because from my point of view this is nonsense:

- the test only checks the appearance of specific keywords and not if the trademark guidance is not followed. It also doesn't detects misusage like ATTACK etc. It only causes that the usage of it is discouraged.
- this also applies to other trademarks. Consequently we have to read the trademark guidelines of [Microsoft](https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks), [Splunk](https://docs.splunk.com/Documentation/StyleGuide/current/StyleGuide/Trademark) and whoever we refer to and check for compliance.
- someone allegedly from MITRE stated in the same issue that the Sigma project is compliant with their rules by mentioning it as requested by their FAQ in the README.

So at least the test logic has to be fixed. Or better, I ask them if the latter is ok and then proceed without the test.

**Comment by nasbench** [comment]
I Agree the current logic of the test isn't really solid at all it's just a "best effort". And you're completely right that we need more clarity regarding the issue of the trademark itself.

I'll leave it to you to decide if you want to close this or not. (You can leave it in case you need a reminder)

**Comment by thomaspatzke** [comment]
Obsoleted through feedback from MITRE.
